### PR TITLE
Azure Pipelines improvements: Unit testing, and test against LDS running inside azure pipelines.

### PR DESCRIPTION
**Pull request by drageset**
The Maven build task now runs the JUnit tests. 

Some of the JUnit tests fire operations against an LDS instance fully configured with a Postgres backend. The LDS/Pg stack is running as a docker-compose task inside the Azure Pipeline.

To run LDS and Postgres services from docker-compose, we:
- Load graphql and sql files from AP Secure Files (accessible from the Library of the pipeline), and store their paths on the AP agent as ENV variables
- Start services from a docker-compose file very similar to `klass-subsets-setup`, pointing to the laoded graphql and sql files as volumes to be used by LDS and Postgres.  This `docker-compose.ci.build.yml` is also a Secure File located in the Library.

To see the docker images, docker-compose YAML and more, go to [this pull request.](https://github.com/statisticsnorway/klass-subsets-setup/pull/6)

Pull request #87 needs to be accepted/merged before this is merged, because this uses elements from that.

### CODE REVIEW

**Comment by drageset** [comment]
I'm struggling with accessing the docker-compose file I've saved as a secure file and downloaded using a Task. I need support on this.

**Comment by drageset** [comment]
ok, got docker-compose to work now! It runs my images successfully

**Comment by drageset** [comment]
I found out that the LDS service created by docker-compose was crashing at startup, but that Azure Pipelines was not giving me this information (I expected it to tell me). By insterting a script that outputs the logs from inside the LDS and Postgres containers, I found out about the crashing LDS instance, and that the problem was with the paths in the volume definition. This way I finally got LDS working properly, and thus the JUnit tests in the Maven build task could speak to the LDS service at localhost:9090 without further ado.

**Review by mmj-ssb — APPROVED** [review]
Had some discussions, everything looks good. Approving.

Something to keep in mind is you should try to avoid such large pull requests with so many things done at the same time, but that is kind of a matter of opinion. You seem to have used this branch to test a lot stuff out so it becomes large by itself for that reason. However, it becomes a little hard to review for someone who has not been a part of the process. Unfortunately we all do this all the time (including myself 💯)!

For example it seems to me this branch and its pull request could be atleast split into Azure Pipelines setup and general test improvements, unless they are tightly coupled together and it has to be this way, but again, for someone who has not been part of the process, it then becomes hard to understand that.

Also there are missing some newlines at the end of some files (a very minor thing).

**Review by runejo — APPROVED** [review]
Good job on making this work! I also agree with @mmj-ssb on splitting into smaller PRs, but on the bright side this is smaller than some of the earlier ones ;-)

**Comment by drageset** [comment]
Thanks both, I'll continue to keep in mind that i should keep the PRs shorter, and think of ways to split the work :)

**Pull request merged**
